### ISSUE TITLE
Cyclone , 

### ISSUE THREAD

**Issue by HiHiCyclone** [Jawon2870/TOCheat#1]
hi jawon , my discord account got ban , so add me on new account mr.hacker_atta   https://discord.gg/wbew55wtQD

**Comment by Jawon2870** [comment]
> 嗨，jawon，我的discord帐户被禁止了，所以把我添加到新帐户mr.hacker_attahttps[://discord.gg/wbew55wtQD](https://discord.gg/wbew55wtQD)



> hi jawon , my discord account got ban , so add me on new account mr.hacker_atta https://discord.gg/wbew55wtQD

hi, i am Jawon
